import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { ContentSdkInitializer } from "@components/ContentSdkInitializer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const key =
        typeof window !== "undefined"
            ? // @ts-ignore 123
              window["__NEXT_HOT_UPDATE__"] || Date.now().toString()
            : "server";

    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
            </head>
            <body>
                <ContentSdkInitializer key={key} />
                {children}
            </body>
        </html>
    );
}
