name: Staging Branch - Push

on:
  push:
    branches: [staging]

# Ensures only one deployment to "staging" environment can be in progress at the same time.
concurrency: staging

jobs:
  # This first step ensures we don't run the workflow if the repository is empty.
  # Feel free to remove this step once your project is pushed to the repository.
  repository-check:
    name: Check if repository is empty
    runs-on: ubuntu-latest
    outputs:
      ready: ${{ steps.webiny-project-js.outputs.ready }}
    steps:
      - uses: actions/checkout@v2

      - name: Check if "webiny.project.js" exists
        id: webiny-project-js
        run: echo "::set-output name=ready::${{ hashFiles('webiny.project.ts') != '' }}"

  build-test-deploy:
    name: Build and test
    needs: repository-check
    runs-on: ubuntu-latest
    if: needs.repository-check.outputs.ready == 'true'
    env:
      NODE_OPTIONS: --max_old_space_size=4096
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.STAGING_AWS_REGION }}
      PULUMI_SECRETS_PROVIDER: ${{ secrets.STAGING_PULUMI_SECRETS_PROVIDER }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.STAGING_PULUMI_CONFIG_PASSPHRASE }}
      WEBINY_PULUMI_BACKEND: ${{ secrets.STAGING_WEBINY_PULUMI_BACKEND }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - uses: actions/checkout@v2

      # Install and cache dependencies.
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}


      - name: Install dependencies
        run: yarn --immutable

      # Run static code analysis.
      - name: Check code formatting
        run: yarn prettier:check

      - name: ESLint
        run: yarn eslint

      # Run unit tests.
      - name: Run unit tests
        run: yarn test:unit

      - name: Deploy
        run: yarn webiny deploy --env staging

      # Run integration tests.
      - name: Run integration tests
        run: yarn test:integration

      # Run end-to-end tests.
      - name: Run end-to-end tests
        run: yarn test:e2e

      # Add additional steps if needed. For example, if you have additional E2E
      # tests done with Cypress (https://www.cypress.io/), you can run them here.
