import type { CSSObject } from "@emotion/react";

// Supported HTML tags.
export type ListHtmlTag = "ol" | "ul";
export type HeadingHtmlTag = "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
export type ParagraphHtmlTag = "p";
export type BlockQuoteHtmlTag = "blockquote";

export type TypographyHTMLTag = HeadingHtmlTag | ParagraphHtmlTag | ListHtmlTag | BlockQuoteHtmlTag;

export type TypographyValue = {
    id: string;
    tag: TypographyHTMLTag;
    name: string;
    css: CSSObject;
    className?: string;
};

/*
 * Contains IDs of the styles and classes generated by Emotion.
 */
export type ThemeEmotionMap = {
    [styleId: string]: {
        id: string;
        tag: TypographyHTMLTag;
        name: string;
        styles?: Record<string, any>;
        // emotion generated class or user provided class
        className: string;
    };
};
